site_name: mydocs
site_url: https://zhengzp2019.github.io/note/
repo_url: https://github.com/zhengzp2019/note
repo_name: note
docs_dir: docs

theme:
  name: windmill

extra_css:
  - ../resources/styles/admonition-fix.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
